Start testing: Jan 04 13:33 UTC
----------------------------------------------------------
2/5 Testing: testPoint
2/5 Test: testPoint
Command: "/workspace/influxdb-cxx/build/bin/testPoint"
Directory: /workspace/influxdb-cxx/build
"testPoint" start time: Jan 04 13:33 UTC
Output:
----------------------------------------------------------
Running 4 test cases...
/workspace/influxdb-cxx/test/testPoint.cxx(26): [1;31;49merror: in "test1": check result[1] == "value=10i" has failed [value=10.00 != value=10i][0;39;49m
/workspace/influxdb-cxx/test/testPoint.cxx(38): [1;31;49merror: in "test2": check result[1] == "value=10i,dvalue=10.1" has failed [value=10.00,dvalue=10.10 != value=10i,dvalue=10.1][0;39;49m
/workspace/influxdb-cxx/test/testPoint.cxx(51): [1;31;49merror: in "test3": check result[1] == "value=10i,dvalue=10.1" has failed [value=10.00,dvalue=10.10 != value=10i,dvalue=10.1][0;39;49m

[1;31;49m*** 3 failures are detected in the test module "Test InfluxDB Point"
[0;39;49m
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"testPoint" end time: Jan 04 13:33 UTC
"testPoint" time elapsed: 00:00:00
----------------------------------------------------------

3/5 Testing: testHttp
3/5 Test: testHttp
Command: "/workspace/influxdb-cxx/build/bin/testHttp"
Directory: /workspace/influxdb-cxx/build
"testHttp" start time: Jan 04 13:33 UTC
Output:
----------------------------------------------------------
Running 2 test cases...
unknown location(0): [4;31;49mfatal error: in "write1": influxdb::InfluxDBException: influx-cxx [HTTP::send]: Response code: 401[0;39;49m
/workspace/influxdb-cxx/test/testHttp.cxx(11): [1;36;49mlast checkpoint: "write1" test entry[0;39;49m

[1;31;49m*** 1 failure is detected in the test module "Test InfluxDB HTTP"
[0;39;49m
<end of output>
Test time =   0.03 sec
----------------------------------------------------------
Test Failed.
"testHttp" end time: Jan 04 13:33 UTC
"testHttp" time elapsed: 00:00:00
----------------------------------------------------------

1/5 Testing: testUdp
1/5 Test: testUdp
Command: "/workspace/influxdb-cxx/build/bin/testUdp"
Directory: /workspace/influxdb-cxx/build
"testUdp" start time: Jan 04 13:33 UTC
Output:
----------------------------------------------------------
Running 2 test cases...

[1;32;49m*** No errors detected
[0;39;49m
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Passed.
"testUdp" end time: Jan 04 13:33 UTC
"testUdp" time elapsed: 00:00:00
----------------------------------------------------------

5/5 Testing: testFactory
5/5 Test: testFactory
Command: "/workspace/influxdb-cxx/build/bin/testFactory"
Directory: /workspace/influxdb-cxx/build
"testFactory" start time: Jan 04 13:33 UTC
Output:
----------------------------------------------------------
Running 3 test cases...

[1;32;49m*** No errors detected
[0;39;49m
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Passed.
"testFactory" end time: Jan 04 13:33 UTC
"testFactory" time elapsed: 00:00:00
----------------------------------------------------------

4/5 Testing: testQuery
4/5 Test: testQuery
Command: "/workspace/influxdb-cxx/build/bin/testQuery"
Directory: /workspace/influxdb-cxx/build
"testQuery" start time: Jan 04 13:33 UTC
Output:
----------------------------------------------------------
Running 5 test cases...
unknown location(0): [4;31;49mfatal error: in "query1": influxdb::InfluxDBException: influx-cxx [HTTP::initCurl]: Database not specified[0;39;49m
/workspace/influxdb-cxx/test/testQuery.cxx(16): [1;36;49mlast checkpoint: "query1" test entry[0;39;49m
unknown location(0): [4;31;49mfatal error: in "timeStampVerify": influxdb::InfluxDBException: influx-cxx [HTTP::initCurl]: Database not specified[0;39;49m
/workspace/influxdb-cxx/test/testQuery.cxx(33): [1;36;49mlast checkpoint: "timeStampVerify" test entry[0;39;49m
unknown location(0): [4;31;49mfatal error: in "queryPerformance": influxdb::InfluxDBException: influx-cxx [HTTP::initCurl]: Database not specified[0;39;49m
/workspace/influxdb-cxx/test/testQuery.cxx(48): [1;36;49mlast checkpoint: "queryPerformance" test entry[0;39;49m
unknown location(0): [4;31;49mfatal error: in "failedQuery1": influxdb::InfluxDBException: influx-cxx [HTTP::initCurl]: Database not specified[0;39;49m
/workspace/influxdb-cxx/test/testQuery.cxx(59): [1;36;49mlast checkpoint: "failedQuery1" test entry[0;39;49m
unknown location(0): [4;31;49mfatal error: in "failedQuery2": influxdb::InfluxDBException: influx-cxx [HTTP::initCurl]: Database not specified[0;39;49m
/workspace/influxdb-cxx/test/testQuery.cxx(66): [1;36;49mlast checkpoint: "failedQuery2" test entry[0;39;49m

[1;31;49m*** 5 failures are detected in the test module "Test InfluxDB Query"
[0;39;49m
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Failed.
"testQuery" end time: Jan 04 13:33 UTC
"testQuery" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jan 04 13:33 UTC
